#!/bin/bash
# $1 - Image
# $2 - Header
# $3 - Info
# $4 - Duration
# $5 - Sound
# $6 - Corner

# Set all the variables
IMAGE=$1
HEADER=$2
INFO=$3
DURATION=$4
SOUND=$5
CORNER=$6

# Delete the old /tmp/kissnotification, if it exists
rm -r /tmp/kissnotification

# Get a reference to teh path of the appplication bundle for KISSNotification
APPLICATIONPATH="/Volumes/Storage/Applications/Selftilities/KISSNotification.app"

# Write all the values into /tmp/kissnotification
echo -e "$IMAGE\n$HEADER\n$INFO\n$DURATION\n$SOUND\n$CORNER" > "/tmp/kissnotification"

# Open a new instance of the app without focusing it
open -n -g "$APPLICATIONPATH"

# Sleep for 1 second
sleep 1

# Delete the /tmp/kissnotification file, just so we dont possibly break things
rm -r /tmp/kissnotification